version: '3.3'
services:
  
  adminserver:
    build: admin-server
    restart: always
    ports:
     - "8765:8765"
    expose:
     - "8765"
    environment:
      spring.security.user.name : awacs
      spring.security.user.password : awacs
  
  socialweb:
    build: smart-pharmacy-user-management
    restart: always
    ports:
     - "9393:9393"
    expose:
     - "9393"
    environment:
     social_login_type: "github, facebook, google"

  authserver:
    build: awacs-cloud-auth-server
    restart: always
    ports:
     - 8100:8100
    expose:
     - 8100
    depends_on:
      - db
    environment:
         spring.boot.admin.client.url: "http://adminserver:8765"
         spring.boot.admin.client.username: 'awacs'
         spring.boot.admin.client.password: 'awacs'
         spring.datasource.url : "jdbc:mysql://db:3306/awacs_cloud"
         spring.datasource.username : root
         spring.datasource.password : secret
         spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
         spring.jpa.show-sql : "true"

  productservice:
    build: smart-pharmacy-product-service
    restart: always
    ports:
     - 8181:8181
    expose:
     - 8181
    depends_on:
      - db
      - jms
    environment:
         SPRING_PROFILES_ACTIVE: dev
         spring.boot.admin.client.url: "http://adminserver:8765"
         spring.boot.admin.client.username: 'awacs'
         spring.boot.admin.client.password: 'awacs'
         awacs.cloud.auth-server.check-token : "http://authserver:8100/oauth/check_token"
         spring.activemq.broker-url : "tcp://jms:61616"
         spring.activemq.in-memory : "false"
         spring.cloud.gcp.project-id: "awacs-cloud-prod"
  

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: awacs_cloud
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d/

  jms:
    image: webcenter/activemq:latest
    restart: always
    ports: 
      - 61616:61616
      - 8161:8161
      - 61613:61613
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin 
      ACTIVEMQ_ADMIN_PASSWORD: admin123
      ACTIVEMQ_CONFIG_QUEUES_controller.events.error: controller.events.error
    deploy:
      mode: replicated
      replicas: 1

  adminer:
     image: adminer
     restart: always
     ports:
     - 8080:8080
     expose:
     - 8080

  nginx:
   build: 
      context: awacs-nginx
      dockerfile: Dockerfile.nginx
   container_name: awacs_nginx
   restart: always
   ports:
   - 80:80
   - 443:443
   expose:
   - 80
   - 443
   links:
    - adminserver
    - socialweb
    - productservice
    - adminer
    - authserver
   depends_on:
   - adminserver
   - socialweb
   - productservice
   - adminer
   - authserver
