version: '3.3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=ON
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: awacs_cloud
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: "devbot"
      MYSQL_PASSWORD: "devbot"
    deploy:
      mode: replicated
      replicas:  1
    volumes: 
      - ../db/:/docker-entrypoint-initdb.d/
 
  adminer:
     image: adminer
     restart: always
     ports:
     - 8080:8080
     expose:
     - 8080
     
  redis:
     image: redis
     ports:
     - 6379:6379
