version: '3.3'

services:
  proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    hostname: proxy
    expose:
      - 1433
    command: /cloud_sql_proxy -instances=awacs-dev:asia-south1:awacs-test-db=tcp:1433
    volumes:
     - ~/.config:/root/.config
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    expose:
    - 1433
    environment: 
      SA_PASSWORD: 'P@ssw0rd#'
      ACCEPT_EULA: Y
      MSSQL_PID: 'Enterprise'
    ports:
     - 1433:1433
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=ON
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: awacs_cloud
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: "devbot"
      MYSQL_PASSWORD: "devbot"
    deploy:
      mode: replicated
      replicas:  1
    volumes: 
      - ../db/:/docker-entrypoint-initdb.d/
 
  adminer:
     image: adminer
     restart: always
     ports:
     - 8080:8080
     expose:
     - 8080
     
  redis:
     image: redis
     ports:
     - 6379:6379
