
CREATE TABLE [dbo].[Users](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ChangePasswordOnLogon] [bit] default 0,
	[PictureId] [bigint] NULL,
	[WorkspaceId] [bigint] NULL,
	[UserSerial] [bigint] NULL,
	[AdhocSerial] [bigint] NULL,
	[Username] [nvarchar](61) NULL,
	[Password] [nvarchar](100) NULL,
	[Role] [nvarchar](60) NULL,
	[ResetKey] [uniqueidentifier] NULL,
	[Name] [nvarchar](50) NULL,
	[Address1] [nvarchar](200) NULL,
	[Address2] [nvarchar](200) NULL,
	[Address3] [nvarchar](200) NULL,
	[CityId] [bigint] NULL,
	[StateId] [bigint] NULL,
	[Country] [nvarchar](max) NULL,
	[PhoneNo] [nvarchar](15) NULL,
	[Mobile] [nvarchar](15) NULL,
	[Email] [nvarchar](60) NULL,
	[ContactPerson] [nvarchar](30) NULL,
	[AwacsMTD] [bit] default 1,
	[IsLiveorderBlocked] [bit] default 0,
	[IsVerify] [bit] default 1,
	[IsAdmin] [bit] default 1,
	[IsAdminDelegate] [bit] default 1,
	[IsAdhoc] [bit] default 1,
	[DeviceId] [nvarchar](50) NULL,
	[GCMRegisterKey] [nvarchar](max) NULL,
	[Type] [nvarchar](50) NULL,
	[LoginType] [nvarchar](50) NULL,
	[ProviderId] [bigint] NULL,
	[ProviderType] [nvarchar](50) NULL,
	[AwacsId] [nvarchar](10) NULL,
	[PSPACode] [nvarchar](61) NULL,
	[UniqueMobileCode] [nvarchar](11) NULL,
	[IsSyncWithEdxhub] [bit] default 1,
	[ThirdPartySoftware] [nvarchar](20) NULL,
	[ThirdPartyCode] [nvarchar](61) NULL,
	[ThirdPartyLUM] [datetime] NULL,
	[ThirdPartyLUT] [datetime] NULL,
	[IsSyncWithThirdParty] [bit] default 1,
	[Dlic1] [nvarchar](100) NULL,
	[Dlic2] [nvarchar](100) NULL,
	[Dlic3] [nvarchar](20) NULL,
	[Dlic4] [nvarchar](20) NULL,
	[Dlic5] [nvarchar](20) NULL,
	[Dlic6] [nvarchar](60) NULL,
	[POBOTP] [nvarchar](6) NULL,
	[GSTIN] [nvarchar](16) NULL,
	[PAN] [nvarchar](20) NULL,
	[XSource] [nvarchar](35) NULL,
	[Pincode] [nvarchar](10) NULL,
	[Remarks] [nvarchar](500) NULL,
	[RegistrationId] [nvarchar](50) NULL,
	[Source] [nvarchar](60) NULL,
	[SourceType] [nvarchar](30) NULL,
	[SignSource] [nvarchar](10) NULL,
	[SignDetail] [nvarchar](50) NULL,
	[CreatedBy] [bigint] NULL,
	[CreatedOn] [datetime] NULL,
	[ModifiedBy] [bigint] NULL,
	[ModifiedOn] [datetime] NULL,
	[Deleted] [bit] default 1,
	[DeletedBy] [bigint] NULL,
	[DeletedOn] [datetime] NULL,
	[IsLicenseExpire] [bit] default 1,
	[LicenseExpireMailOn] [datetime] NULL,
	[Sync] [bit] default 1,
	[LastActivity] [datetime] NULL,
	[OrderSeq] [bigint] NULL,
	[AppVersion] [nvarchar](25) NULL,
	[OSVersion] [nvarchar](25) NULL,
	[Platform] [nvarchar](25) NULL,
	[UserKind] [nvarchar](15) NULL,
	[Bank] [nvarchar](10) NULL,
	[IFSCCode] [nvarchar](15) NULL,
	[CorpId] [nvarchar](32) NULL,
	[UserId] [nvarchar](32) NULL,
	[AccountNumber] [nvarchar](20) NULL,
	[AppPackage] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


SET IDENTITY_INSERT dbo.Users ON

INSERT INTO [dbo].[Users]([Id] ,[Username],	[Password], [Role], [Name],[Address1],[Address2],[Address3],[AwacsMTD]) VALUES ('1','admin','$2a$08$qvrzQZ7jJ7oy2p/msL4M0.l83Cd0jNsX6AJUitbgRXGzge4j035ha','Customer','Girish Mahajan', '501 Nakshtra Galaxy', 'CHSL Majiwada', 'Maharashtra', 1);

INSERT INTO [dbo].[Users]([Id] ,[Username],	[Password], [Role], [Name],[Address1],[Address2],[Address3],[AwacsMTD]) VALUES ('2','wakandagrpc','$2y$08$byB9gh2IvpDLA9p7URsp5OgY0ydCwmKxArUL5Jf4tJShBJW1ZlCI.','Implicit','Grpc Internal User', 'Nobody', 'Nowhere', 'Maharashtra', 1);

SET IDENTITY_INSERT dbo.Users OFF
