apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jms
  name: jms
spec:
  ports:
  - name: "61616"
    port: 61616
    targetPort: 61616
  - name: "8161"
    port: 8161
    targetPort: 8161
  - name: "61613"
    port: 61613
    targetPort: 61613
  selector:
    io.kompose.service: jms
status:
  loadBalancer: {}
